### ISSUE TITLE
Имелось ввиду именно фигура из строк (но все равно ОК)

### ISSUE THREAD

**Issue by tallinn-learning** [VeronikaOstrovski/homework02.#1]
https://github.com/VeronikaOstrovski/homework02/blob/fdaa675f8932d7f224599150a875bc489f79471d/src/Main1.java#L4

       System.out.println("  *  ");
        System.out.println(" *** ");
        System.out.println("*****");
        System.out.println(" *** ");
        System.out.println("  *  ");

**Comment by VeronikaOstrovski** [comment]
Хорошо. Вас поняла )))
